# This file is generated by scripts/preprocess_assets.py.

FIGURE_PATHS = {'fig1_abonnement': 'assets/figures/figur-1-abonnement.png', 'fig1_omsetning': 'assets/figures/figur-1-omsetning.png', 'fig2_abonnement': 'assets/figures/figur-2-abonnement-trend.png', 'fig2_omsetning': 'assets/figures/figur-2-omsetning-trend.png', 'fig3_privat': 'assets/figures/figur-3-privat.png', 'fig3_bedrift': 'assets/figures/figur-3-bedrift.png'}
EXPORT_PATHS = {'fig1_abonnement': 'assets/exports/figur-1-abonnement.xlsx', 'fig1_omsetning': 'assets/exports/figur-1-omsetning.xlsx', 'fig2_abonnement': 'assets/exports/figur-2-abonnement-trend.xlsx', 'fig2_omsetning': 'assets/exports/figur-2-omsetning-trend.xlsx', 'fig3_privat': 'assets/exports/figur-3-privat.xlsx', 'fig3_bedrift': 'assets/exports/figur-3-bedrift.xlsx'}

FIG1_PERIOD_TEXT = 'Endring fra 2024 til 2025'
FIG1_SUMMARY_LINES = ['<strong>Lyse Tele (Ice)</strong> øker i omsetningsandel (<strong>10,8 %&rarr;11,8 %</strong>) og øker i abonnementsandel (<strong>16,0 %&rarr;17,1 %</strong>).', '<strong>Telenor</strong> går ned i omsetningsandel (<strong>50,8 %&rarr;50,6 %</strong>) og går ned i abonnementsandel (<strong>41,3 %&rarr;40,4 %</strong>).', '<strong>Telia</strong> går ned i omsetningsandel (<strong>31,5 %&rarr;30,8 %</strong>) og går ned i abonnementsandel (<strong>33,7 %&rarr;32,8 %</strong>).', '<strong>Øvrige</strong> går ned i omsetningsandel (<strong>6,9 %&rarr;6,7 %</strong>) og øker i abonnementsandel (<strong>8,9 %&rarr;9,6 %</strong>).']

FIG2_NOTE = 'Lyse Tele (Ice) når 20 % av omsetningen rundt 2035.'

FIG3_PERIOD_TEXT = 'Endring fra 2024 til 2025'
FIG3_SUMMARY_LINES = ['<strong>Lyse Tele (Ice)</strong> øker i privatmarkedet (<strong>20,7 %&rarr;21,9 %</strong>) og øker i bedriftsmarkedet (<strong>4,2 %&rarr;5,2 %</strong>).', '<strong>Telenor</strong> går ned i privatmarkedet (<strong>37,3 %&rarr;36,3 %</strong>) og går ned i bedriftsmarkedet (<strong>51,5 %&rarr;50,7 %</strong>).', '<strong>Telia</strong> går ned i privatmarkedet (<strong>32,7 %&rarr;31,7 %</strong>) og går ned i bedriftsmarkedet (<strong>36,2 %&rarr;35,7 %</strong>).', '<strong>Øvrige</strong> øker i privatmarkedet (<strong>9,3 %&rarr;10,1 %</strong>) og øker i bedriftsmarkedet (<strong>8,0 %&rarr;8,3 %</strong>).']
